///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace BellWorkflow
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the BellWorkflowRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("1d75cf94-0982-4020-b055-83f8bed454c0")]
    public partial class BellWorkflowRepository : RepoGenBaseFolder
    {
        static BellWorkflowRepository instance = new BellWorkflowRepository();
        BellWorkflowRepositoryFolders.AdobeAcrobatProDCTrunk05242020AppFolder _adobeacrobatprodctrunk05242020;
        BellWorkflowRepositoryFolders.AcrobatAppFolder _acrobat;
        BellWorkflowRepositoryFolders.OpenAppFolder _open;
        BellWorkflowRepositoryFolders.ShareLinkWithOthersAppFolder _sharelinkwithothers;
        BellWorkflowRepositoryFolders.CloseSharedFileAppFolder _closesharedfile;
        BellWorkflowRepositoryFolders.PressSignOutFromProfileAppFolder _presssignoutfromprofile;
        BellWorkflowRepositoryFolders.AdobeIDAppFolder _adobeid;
        BellWorkflowRepositoryFolders.BlankAppFolder _blank;
        BellWorkflowRepositoryFolders.SampleFilePdfAdobeAcrobatProDCTAppFolder _samplefilepdfadobeacrobatprodct;
        BellWorkflowRepositoryFolders.SampleFilePdfOpenedFromAdobeDocumeAppFolder _samplefilepdfopenedfromadobedocume;
        BellWorkflowRepositoryFolders.AdobeLicensingAppFolder _adobelicensing;
        RepoItemInfo _sharebuttonclickInfo;

        /// <summary>
        /// Gets the singleton class instance representing the BellWorkflowRepository element repository.
        /// </summary>
        [RepositoryFolder("1d75cf94-0982-4020-b055-83f8bed454c0")]
        public static BellWorkflowRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public BellWorkflowRepository() 
            : base("BellWorkflowRepository", "/", null, 0, false, "1d75cf94-0982-4020-b055-83f8bed454c0", ".\\RepositoryImages\\BellWorkflowRepository1d75cf94.rximgres")
        {
            _adobeacrobatprodctrunk05242020 = new BellWorkflowRepositoryFolders.AdobeAcrobatProDCTrunk05242020AppFolder(this);
            _acrobat = new BellWorkflowRepositoryFolders.AcrobatAppFolder(this);
            _open = new BellWorkflowRepositoryFolders.OpenAppFolder(this);
            _sharelinkwithothers = new BellWorkflowRepositoryFolders.ShareLinkWithOthersAppFolder(this);
            _closesharedfile = new BellWorkflowRepositoryFolders.CloseSharedFileAppFolder(this);
            _presssignoutfromprofile = new BellWorkflowRepositoryFolders.PressSignOutFromProfileAppFolder(this);
            _adobeid = new BellWorkflowRepositoryFolders.AdobeIDAppFolder(this);
            _blank = new BellWorkflowRepositoryFolders.BlankAppFolder(this);
            _samplefilepdfadobeacrobatprodct = new BellWorkflowRepositoryFolders.SampleFilePdfAdobeAcrobatProDCTAppFolder(this);
            _samplefilepdfopenedfromadobedocume = new BellWorkflowRepositoryFolders.SampleFilePdfOpenedFromAdobeDocumeAppFolder(this);
            _adobelicensing = new BellWorkflowRepositoryFolders.AdobeLicensingAppFolder(this);
            _sharebuttonclickInfo = new RepoItemInfo(this, "ShareButtonClick", "/form[@title>'SampleFile.pdf - Adobe Acrobat']/element[@instance='1']/element[@instance='0']/element[@instance='0']", 30000, null, "08456260-131a-4fd7-bc39-50a152ba358a");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("1d75cf94-0982-4020-b055-83f8bed454c0")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ShareButtonClick item.
        /// </summary>
        [RepositoryItem("08456260-131a-4fd7-bc39-50a152ba358a")]
        public virtual Ranorex.Unknown ShareButtonClick
        {
            get
            {
                 return _sharebuttonclickInfo.CreateAdapter<Ranorex.Unknown>(true);
            }
        }

        /// <summary>
        /// The ShareButtonClick item info.
        /// </summary>
        [RepositoryItemInfo("08456260-131a-4fd7-bc39-50a152ba358a")]
        public virtual RepoItemInfo ShareButtonClickInfo
        {
            get
            {
                return _sharebuttonclickInfo;
            }
        }

        /// <summary>
        /// The AdobeAcrobatProDCTrunk05242020 folder.
        /// </summary>
        [RepositoryFolder("99cb748a-083a-4e8b-9d35-fade975a3cb1")]
        public virtual BellWorkflowRepositoryFolders.AdobeAcrobatProDCTrunk05242020AppFolder AdobeAcrobatProDCTrunk05242020
        {
            get { return _adobeacrobatprodctrunk05242020; }
        }

        /// <summary>
        /// The Acrobat folder.
        /// </summary>
        [RepositoryFolder("a0fa3cc0-d2d9-44dc-80f3-df9d9b419e6c")]
        public virtual BellWorkflowRepositoryFolders.AcrobatAppFolder Acrobat
        {
            get { return _acrobat; }
        }

        /// <summary>
        /// The Open folder.
        /// </summary>
        [RepositoryFolder("68d94354-495f-41e8-8632-251efb787a6b")]
        public virtual BellWorkflowRepositoryFolders.OpenAppFolder Open
        {
            get { return _open; }
        }

        /// <summary>
        /// The ShareLinkWithOthers folder.
        /// </summary>
        [RepositoryFolder("8d7fbd33-4d95-4811-be74-a2bf9dc1d34f")]
        public virtual BellWorkflowRepositoryFolders.ShareLinkWithOthersAppFolder ShareLinkWithOthers
        {
            get { return _sharelinkwithothers; }
        }

        /// <summary>
        /// The CloseSharedFile folder.
        /// </summary>
        [RepositoryFolder("f79cd8a7-bb8d-4803-887f-b13195641cdc")]
        public virtual BellWorkflowRepositoryFolders.CloseSharedFileAppFolder CloseSharedFile
        {
            get { return _closesharedfile; }
        }

        /// <summary>
        /// The PressSignOutFromProfile folder.
        /// </summary>
        [RepositoryFolder("b904a0a4-cb78-4c09-b0f1-1b5e2b205903")]
        public virtual BellWorkflowRepositoryFolders.PressSignOutFromProfileAppFolder PressSignOutFromProfile
        {
            get { return _presssignoutfromprofile; }
        }

        /// <summary>
        /// The AdobeID folder.
        /// </summary>
        [RepositoryFolder("5c192983-ce27-4b7e-861d-19ed930493b2")]
        public virtual BellWorkflowRepositoryFolders.AdobeIDAppFolder AdobeID
        {
            get { return _adobeid; }
        }

        /// <summary>
        /// The Blank folder.
        /// </summary>
        [RepositoryFolder("b9446456-d3a8-4735-9e26-e170de263e42")]
        public virtual BellWorkflowRepositoryFolders.BlankAppFolder Blank
        {
            get { return _blank; }
        }

        /// <summary>
        /// The SampleFilePdfAdobeAcrobatProDCT folder.
        /// </summary>
        [RepositoryFolder("ed020dac-9d58-49da-94ba-bf350c7176cd")]
        public virtual BellWorkflowRepositoryFolders.SampleFilePdfAdobeAcrobatProDCTAppFolder SampleFilePdfAdobeAcrobatProDCT
        {
            get { return _samplefilepdfadobeacrobatprodct; }
        }

        /// <summary>
        /// The SampleFilePdfOpenedFromAdobeDocume folder.
        /// </summary>
        [RepositoryFolder("3ce5c783-f83a-45c4-b2ef-e9984fea4ed1")]
        public virtual BellWorkflowRepositoryFolders.SampleFilePdfOpenedFromAdobeDocumeAppFolder SampleFilePdfOpenedFromAdobeDocume
        {
            get { return _samplefilepdfopenedfromadobedocume; }
        }

        /// <summary>
        /// The AdobeLicensing folder.
        /// </summary>
        [RepositoryFolder("1775bb76-1993-43fe-b7ca-7fc02ae0d72c")]
        public virtual BellWorkflowRepositoryFolders.AdobeLicensingAppFolder AdobeLicensing
        {
            get { return _adobelicensing; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class BellWorkflowRepositoryFolders
    {
        /// <summary>
        /// The AdobeAcrobatProDCTrunk05242020AppFolder folder.
        /// </summary>
        [RepositoryFolder("99cb748a-083a-4e8b-9d35-fade975a3cb1")]
        public partial class AdobeAcrobatProDCTrunk05242020AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fileInfo;
            RepoItemInfo _avlavviewInfo;
            RepoItemInfo _avlavview1Info;
            RepoItemInfo _avlavview2Info;
            RepoItemInfo _clickprofileInfo;
            RepoItemInfo _somemenuitemInfo;
            RepoItemInfo _avlavview3Info;

            /// <summary>
            /// Creates a new AdobeAcrobatProDCTrunk05242020  folder.
            /// </summary>
            public AdobeAcrobatProDCTrunk05242020AppFolder(RepoGenBaseFolder parentFolder) :
                    base("AdobeAcrobatProDCTrunk05242020", "/form[@title>'Adobe Acrobat Pro DC (Tru']", parentFolder, 30000, null, true, "99cb748a-083a-4e8b-9d35-fade975a3cb1", "")
            {
                _fileInfo = new RepoItemInfo(this, "File", "?/?/element[@controlid='1100']/toolbar[@accessiblerole='ToolBar']/menuitem[@accessiblename='File']", 30000, null, "7c1fbdb9-2289-462f-892b-60424dc5d0f2");
                _avlavviewInfo = new RepoItemInfo(this, "AVLAVView", "element[@instance='1']/element[@instance='0']/element[@instance='0']", 30000, null, "cf6b3495-6b10-4eea-b17a-45946118d959");
                _avlavview1Info = new RepoItemInfo(this, "AVLAVView1", "element[@instance='1']/?/?/element[@instance='4']/element[@instance='0']/element[@instance='0']/element[@instance='0']", 30000, null, "f43eaada-a700-447b-8913-5db5ff00955f");
                _avlavview2Info = new RepoItemInfo(this, "AVLAVView2", "element[@instance='1']/element[@instance='0']/element[@instance='1']", 30000, null, "3b914ddd-8e08-4ee4-8c51-916461852aa7");
                _clickprofileInfo = new RepoItemInfo(this, "ClickProfile", "element[@instance='0']", 30000, null, "68dfc908-148c-4019-8b78-6ef8800aec0d");
                _somemenuitemInfo = new RepoItemInfo(this, "SomeMenuItem", ".//toolbar[@accessiblerole='ToolBar']/menuitem[@accessiblename='🗙']", 30000, null, "0d1f555e-7a0c-4eee-a02e-e57cc682adaa");
                _avlavview3Info = new RepoItemInfo(this, "AVLAVView3", "element[@instance='1']/element/element[@instance='0']/element[@instance='1']/element[@class='AVL_AVView']", 30000, null, "2f319dc7-830f-4749-90e4-daad4204fae5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("99cb748a-083a-4e8b-9d35-fade975a3cb1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("99cb748a-083a-4e8b-9d35-fade975a3cb1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The File item.
            /// </summary>
            [RepositoryItem("7c1fbdb9-2289-462f-892b-60424dc5d0f2")]
            public virtual Ranorex.MenuItem File
            {
                get
                {
                    return _fileInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The File item info.
            /// </summary>
            [RepositoryItemInfo("7c1fbdb9-2289-462f-892b-60424dc5d0f2")]
            public virtual RepoItemInfo FileInfo
            {
                get
                {
                    return _fileInfo;
                }
            }

            /// <summary>
            /// The AVLAVView item.
            /// </summary>
            [RepositoryItem("cf6b3495-6b10-4eea-b17a-45946118d959")]
            public virtual Ranorex.Unknown AVLAVView
            {
                get
                {
                    return _avlavviewInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The AVLAVView item info.
            /// </summary>
            [RepositoryItemInfo("cf6b3495-6b10-4eea-b17a-45946118d959")]
            public virtual RepoItemInfo AVLAVViewInfo
            {
                get
                {
                    return _avlavviewInfo;
                }
            }

            /// <summary>
            /// The AVLAVView1 item.
            /// </summary>
            [RepositoryItem("f43eaada-a700-447b-8913-5db5ff00955f")]
            public virtual Ranorex.Unknown AVLAVView1
            {
                get
                {
                    return _avlavview1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The AVLAVView1 item info.
            /// </summary>
            [RepositoryItemInfo("f43eaada-a700-447b-8913-5db5ff00955f")]
            public virtual RepoItemInfo AVLAVView1Info
            {
                get
                {
                    return _avlavview1Info;
                }
            }

            /// <summary>
            /// The AVLAVView2 item.
            /// </summary>
            [RepositoryItem("3b914ddd-8e08-4ee4-8c51-916461852aa7")]
            public virtual Ranorex.Unknown AVLAVView2
            {
                get
                {
                    return _avlavview2Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The AVLAVView2 item info.
            /// </summary>
            [RepositoryItemInfo("3b914ddd-8e08-4ee4-8c51-916461852aa7")]
            public virtual RepoItemInfo AVLAVView2Info
            {
                get
                {
                    return _avlavview2Info;
                }
            }

            /// <summary>
            /// The ClickProfile item.
            /// </summary>
            [RepositoryItem("68dfc908-148c-4019-8b78-6ef8800aec0d")]
            public virtual Ranorex.Unknown ClickProfile
            {
                get
                {
                    return _clickprofileInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ClickProfile item info.
            /// </summary>
            [RepositoryItemInfo("68dfc908-148c-4019-8b78-6ef8800aec0d")]
            public virtual RepoItemInfo ClickProfileInfo
            {
                get
                {
                    return _clickprofileInfo;
                }
            }

            /// <summary>
            /// The SomeMenuItem item.
            /// </summary>
            [RepositoryItem("0d1f555e-7a0c-4eee-a02e-e57cc682adaa")]
            public virtual Ranorex.MenuItem SomeMenuItem
            {
                get
                {
                    return _somemenuitemInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The SomeMenuItem item info.
            /// </summary>
            [RepositoryItemInfo("0d1f555e-7a0c-4eee-a02e-e57cc682adaa")]
            public virtual RepoItemInfo SomeMenuItemInfo
            {
                get
                {
                    return _somemenuitemInfo;
                }
            }

            /// <summary>
            /// The AVLAVView3 item.
            /// </summary>
            [RepositoryItem("2f319dc7-830f-4749-90e4-daad4204fae5")]
            public virtual Ranorex.Unknown AVLAVView3
            {
                get
                {
                    return _avlavview3Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The AVLAVView3 item info.
            /// </summary>
            [RepositoryItemInfo("2f319dc7-830f-4749-90e4-daad4204fae5")]
            public virtual RepoItemInfo AVLAVView3Info
            {
                get
                {
                    return _avlavview3Info;
                }
            }
        }

        /// <summary>
        /// The AcrobatAppFolder folder.
        /// </summary>
        [RepositoryFolder("a0fa3cc0-d2d9-44dc-80f3-df9d9b419e6c")]
        public partial class AcrobatAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _openctrlplusoInfo;

            /// <summary>
            /// Creates a new Acrobat  folder.
            /// </summary>
            public AcrobatAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Acrobat", "/contextmenu[@processname='Acrobat']", parentFolder, 30000, null, false, "a0fa3cc0-d2d9-44dc-80f3-df9d9b419e6c", "")
            {
                _openctrlplusoInfo = new RepoItemInfo(this, "OpenCtrlPlusO", "?/?/menuitem[@accessiblename='Open... Ctrl+O']", 30000, null, "f20cfa22-c48f-4138-9756-4fdf121ec56c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a0fa3cc0-d2d9-44dc-80f3-df9d9b419e6c")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a0fa3cc0-d2d9-44dc-80f3-df9d9b419e6c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OpenCtrlPlusO item.
            /// </summary>
            [RepositoryItem("f20cfa22-c48f-4138-9756-4fdf121ec56c")]
            public virtual Ranorex.MenuItem OpenCtrlPlusO
            {
                get
                {
                    return _openctrlplusoInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The OpenCtrlPlusO item info.
            /// </summary>
            [RepositoryItemInfo("f20cfa22-c48f-4138-9756-4fdf121ec56c")]
            public virtual RepoItemInfo OpenCtrlPlusOInfo
            {
                get
                {
                    return _openctrlplusoInfo;
                }
            }
        }

        /// <summary>
        /// The OpenAppFolder folder.
        /// </summary>
        [RepositoryFolder("68d94354-495f-41e8-8632-251efb787a6b")]
        public partial class OpenAppFolder : RepoGenBaseFolder
        {
            BellWorkflowRepositoryFolders.ShellViewFolder _shellview;
            RepoItemInfo _toolbar1001Info;
            RepoItemInfo _systemitemnamedisplayInfo;
            RepoItemInfo _buttonopenInfo;

            /// <summary>
            /// Creates a new Open  folder.
            /// </summary>
            public OpenAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Open", "/form[@title='Open']", parentFolder, 30000, null, true, "68d94354-495f-41e8-8632-251efb787a6b", "")
            {
                _shellview = new BellWorkflowRepositoryFolders.ShellViewFolder(this);
                _toolbar1001Info = new RepoItemInfo(this, "ToolBar1001", "element[@class='WorkerW']/?/?/element[@controlid='41477']//toolbar[@controlid='1001']", 30000, null, "d92418b2-3c03-4e21-8131-ee16a7362961");
                _systemitemnamedisplayInfo = new RepoItemInfo(this, "SystemItemNameDisplay", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']/?/?/listitem[@automationid='0']/text[@automationid='System.ItemNameDisplay']", 30000, null, "65fd9bee-9743-4495-9d83-c1c94983d551");
                _buttonopenInfo = new RepoItemInfo(this, "ButtonOpen", "button[@text='&Open']", 30000, null, "d4abb799-4b9b-4475-8795-177a17fb11c1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("68d94354-495f-41e8-8632-251efb787a6b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("68d94354-495f-41e8-8632-251efb787a6b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ToolBar1001 item.
            /// </summary>
            [RepositoryItem("d92418b2-3c03-4e21-8131-ee16a7362961")]
            public virtual Ranorex.ToolBar ToolBar1001
            {
                get
                {
                    return _toolbar1001Info.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The ToolBar1001 item info.
            /// </summary>
            [RepositoryItemInfo("d92418b2-3c03-4e21-8131-ee16a7362961")]
            public virtual RepoItemInfo ToolBar1001Info
            {
                get
                {
                    return _toolbar1001Info;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item.
            /// </summary>
            [RepositoryItem("65fd9bee-9743-4495-9d83-c1c94983d551")]
            public virtual Ranorex.Text SystemItemNameDisplay
            {
                get
                {
                    return _systemitemnamedisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item info.
            /// </summary>
            [RepositoryItemInfo("65fd9bee-9743-4495-9d83-c1c94983d551")]
            public virtual RepoItemInfo SystemItemNameDisplayInfo
            {
                get
                {
                    return _systemitemnamedisplayInfo;
                }
            }

            /// <summary>
            /// The ButtonOpen item.
            /// </summary>
            [RepositoryItem("d4abb799-4b9b-4475-8795-177a17fb11c1")]
            public virtual Ranorex.Button ButtonOpen
            {
                get
                {
                    return _buttonopenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOpen item info.
            /// </summary>
            [RepositoryItemInfo("d4abb799-4b9b-4475-8795-177a17fb11c1")]
            public virtual RepoItemInfo ButtonOpenInfo
            {
                get
                {
                    return _buttonopenInfo;
                }
            }

            /// <summary>
            /// The ShellView folder.
            /// </summary>
            [RepositoryFolder("d51b100e-4b57-4b26-810d-9f08476c963e")]
            public virtual BellWorkflowRepositoryFolders.ShellViewFolder ShellView
            {
                get { return _shellview; }
            }
        }

        /// <summary>
        /// The ShellViewFolder folder.
        /// </summary>
        [RepositoryFolder("d51b100e-4b57-4b26-810d-9f08476c963e")]
        public partial class ShellViewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _itemsviewInfo;
            RepoItemInfo _systemitemnamedisplay1Info;
            RepoItemInfo _nameInfo;

            /// <summary>
            /// Creates a new ShellView  folder.
            /// </summary>
            public ShellViewFolder(RepoGenBaseFolder parentFolder) :
                    base("ShellView", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']", parentFolder, 30000, null, false, "d51b100e-4b57-4b26-810d-9f08476c963e", "")
            {
                _itemsviewInfo = new RepoItemInfo(this, "ItemsView", "?/?/list[@accessiblename='Items View']", 30000, null, "db28afc7-fd5a-43ac-bedd-d6b965337142");
                _systemitemnamedisplay1Info = new RepoItemInfo(this, "SystemItemNameDisplay1", "?/?/listitem[@automationid='0']/text", 30000, null, "0053ff64-880c-4816-966b-0933d7c8d0e3");
                _nameInfo = new RepoItemInfo(this, "Name", "?/?/listitem[@automationid='0']/text[@name='Name']", 30000, null, "cb5a0e72-c6af-47b9-ac3a-b9bc7c34768b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d51b100e-4b57-4b26-810d-9f08476c963e")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d51b100e-4b57-4b26-810d-9f08476c963e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ItemsView item.
            /// </summary>
            [RepositoryItem("db28afc7-fd5a-43ac-bedd-d6b965337142")]
            public virtual Ranorex.List ItemsView
            {
                get
                {
                    return _itemsviewInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The ItemsView item info.
            /// </summary>
            [RepositoryItemInfo("db28afc7-fd5a-43ac-bedd-d6b965337142")]
            public virtual RepoItemInfo ItemsViewInfo
            {
                get
                {
                    return _itemsviewInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay1 item.
            /// </summary>
            [RepositoryItem("0053ff64-880c-4816-966b-0933d7c8d0e3")]
            public virtual Ranorex.Text SystemItemNameDisplay1
            {
                get
                {
                    return _systemitemnamedisplay1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay1 item info.
            /// </summary>
            [RepositoryItemInfo("0053ff64-880c-4816-966b-0933d7c8d0e3")]
            public virtual RepoItemInfo SystemItemNameDisplay1Info
            {
                get
                {
                    return _systemitemnamedisplay1Info;
                }
            }

            /// <summary>
            /// The Name item.
            /// </summary>
            [RepositoryItem("cb5a0e72-c6af-47b9-ac3a-b9bc7c34768b")]
            public virtual Ranorex.Text Name
            {
                get
                {
                    return _nameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Name item info.
            /// </summary>
            [RepositoryItemInfo("cb5a0e72-c6af-47b9-ac3a-b9bc7c34768b")]
            public virtual RepoItemInfo NameInfo
            {
                get
                {
                    return _nameInfo;
                }
            }
        }

        /// <summary>
        /// The ShareLinkWithOthersAppFolder folder.
        /// </summary>
        [RepositoryFolder("8d7fbd33-4d95-4811-be74-a2bf9dc1d34f")]
        public partial class ShareLinkWithOthersAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _emailidfieldInfo;

            /// <summary>
            /// Creates a new ShareLinkWithOthers  folder.
            /// </summary>
            public ShareLinkWithOthersAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ShareLinkWithOthers", "/form[@title='Share link with others']", parentFolder, 30000, null, true, "8d7fbd33-4d95-4811-be74-a2bf9dc1d34f", "")
            {
                _emailidfieldInfo = new RepoItemInfo(this, "EmailIdField", "element[@class='AVL_AVView']", 30000, null, "f2c94983-4aa8-46c6-95fe-8679c089b779");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8d7fbd33-4d95-4811-be74-a2bf9dc1d34f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8d7fbd33-4d95-4811-be74-a2bf9dc1d34f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EmailIdField item.
            /// </summary>
            [RepositoryItem("f2c94983-4aa8-46c6-95fe-8679c089b779")]
            public virtual Ranorex.Unknown EmailIdField
            {
                get
                {
                    return _emailidfieldInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The EmailIdField item info.
            /// </summary>
            [RepositoryItemInfo("f2c94983-4aa8-46c6-95fe-8679c089b779")]
            public virtual RepoItemInfo EmailIdFieldInfo
            {
                get
                {
                    return _emailidfieldInfo;
                }
            }
        }

        /// <summary>
        /// The CloseSharedFileAppFolder folder.
        /// </summary>
        [RepositoryFolder("f79cd8a7-bb8d-4803-887f-b13195641cdc")]
        public partial class CloseSharedFileAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new CloseSharedFile  folder.
            /// </summary>
            public CloseSharedFileAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CloseSharedFile", "/form[@title='Close shared file']", parentFolder, 30000, null, true, "f79cd8a7-bb8d-4803-887f-b13195641cdc", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "?/?/button[@text='OK']", 30000, null, "8abe8ff8-a32c-4d80-abec-9db278f764f9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f79cd8a7-bb8d-4803-887f-b13195641cdc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f79cd8a7-bb8d-4803-887f-b13195641cdc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("8abe8ff8-a32c-4d80-abec-9db278f764f9")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("8abe8ff8-a32c-4d80-abec-9db278f764f9")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The PressSignOutFromProfileAppFolder folder.
        /// </summary>
        [RepositoryFolder("b904a0a4-cb78-4c09-b0f1-1b5e2b205903")]
        public partial class PressSignOutFromProfileAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _avlavviewInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new PressSignOutFromProfile  folder.
            /// </summary>
            public PressSignOutFromProfileAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PressSignOutFromProfile", "/form[@title='']", parentFolder, 30000, null, true, "b904a0a4-cb78-4c09-b0f1-1b5e2b205903", "")
            {
                _avlavviewInfo = new RepoItemInfo(this, "AVLAVView", "element[@class='AVL_AVView']", 30000, null, "3ace6fbb-83a1-4a38-945f-1a92084762e5");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "ce3f955c-c322-4acd-88fe-79982df17868");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b904a0a4-cb78-4c09-b0f1-1b5e2b205903")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b904a0a4-cb78-4c09-b0f1-1b5e2b205903")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AVLAVView item.
            /// </summary>
            [RepositoryItem("3ace6fbb-83a1-4a38-945f-1a92084762e5")]
            public virtual Ranorex.Unknown AVLAVView
            {
                get
                {
                    return _avlavviewInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The AVLAVView item info.
            /// </summary>
            [RepositoryItemInfo("3ace6fbb-83a1-4a38-945f-1a92084762e5")]
            public virtual RepoItemInfo AVLAVViewInfo
            {
                get
                {
                    return _avlavviewInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("ce3f955c-c322-4acd-88fe-79982df17868")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("ce3f955c-c322-4acd-88fe-79982df17868")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The AdobeIDAppFolder folder.
        /// </summary>
        [RepositoryFolder("5c192983-ce27-4b7e-861d-19ed930493b2")]
        public partial class AdobeIDAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _emailpageemailfieldInfo;
            RepoItemInfo _routeInfo;
            RepoItemInfo _continueInfo;
            RepoItemInfo _canvasgridInfo;

            /// <summary>
            /// Creates a new AdobeID  folder.
            /// </summary>
            public AdobeIDAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AdobeID", "/dom[@domain='auth.services.adobe.com']", parentFolder, 30000, null, false, "5c192983-ce27-4b7e-861d-19ed930493b2", "")
            {
                _emailpageemailfieldInfo = new RepoItemInfo(this, "EmailPageEmailField", ".//input[#'EmailPage-EmailField']", 30000, null, "604aed11-588a-4998-9d87-b14affd4c37c");
                _routeInfo = new RepoItemInfo(this, "Route", ".//div[#'App']//section/section/?/?/div", 30000, null, "d6e18532-16c4-434c-b51e-11b1f66bf0ba");
                _continueInfo = new RepoItemInfo(this, "Continue", ".//form[#'EmailForm']/section[2]//span[@innertext='Continue']", 30000, null, "c4a5c6ea-acdd-4665-8c94-8a73c8da8d55");
                _canvasgridInfo = new RepoItemInfo(this, "CanvasGrid", ".//div[#'App']//section/section", 30000, null, "773135d2-a3f9-43bc-a57f-075741e24c75");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5c192983-ce27-4b7e-861d-19ed930493b2")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5c192983-ce27-4b7e-861d-19ed930493b2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EmailPageEmailField item.
            /// </summary>
            [RepositoryItem("604aed11-588a-4998-9d87-b14affd4c37c")]
            public virtual Ranorex.InputTag EmailPageEmailField
            {
                get
                {
                    return _emailpageemailfieldInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The EmailPageEmailField item info.
            /// </summary>
            [RepositoryItemInfo("604aed11-588a-4998-9d87-b14affd4c37c")]
            public virtual RepoItemInfo EmailPageEmailFieldInfo
            {
                get
                {
                    return _emailpageemailfieldInfo;
                }
            }

            /// <summary>
            /// The Route item.
            /// </summary>
            [RepositoryItem("d6e18532-16c4-434c-b51e-11b1f66bf0ba")]
            public virtual Ranorex.DivTag Route
            {
                get
                {
                    return _routeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Route item info.
            /// </summary>
            [RepositoryItemInfo("d6e18532-16c4-434c-b51e-11b1f66bf0ba")]
            public virtual RepoItemInfo RouteInfo
            {
                get
                {
                    return _routeInfo;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("c4a5c6ea-acdd-4665-8c94-8a73c8da8d55")]
            public virtual Ranorex.SpanTag Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("c4a5c6ea-acdd-4665-8c94-8a73c8da8d55")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }

            /// <summary>
            /// The CanvasGrid item.
            /// </summary>
            [RepositoryItem("773135d2-a3f9-43bc-a57f-075741e24c75")]
            public virtual Ranorex.SectionTag CanvasGrid
            {
                get
                {
                    return _canvasgridInfo.CreateAdapter<Ranorex.SectionTag>(true);
                }
            }

            /// <summary>
            /// The CanvasGrid item info.
            /// </summary>
            [RepositoryItemInfo("773135d2-a3f9-43bc-a57f-075741e24c75")]
            public virtual RepoItemInfo CanvasGridInfo
            {
                get
                {
                    return _canvasgridInfo;
                }
            }
        }

        /// <summary>
        /// The BlankAppFolder folder.
        /// </summary>
        [RepositoryFolder("b9446456-d3a8-4735-9e26-e170de263e42")]
        public partial class BlankAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Blank  folder.
            /// </summary>
            public BlankAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Blank", "/dom[@domain='']", parentFolder, 30000, null, false, "b9446456-d3a8-4735-9e26-e170de263e42", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b9446456-d3a8-4735-9e26-e170de263e42")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b9446456-d3a8-4735-9e26-e170de263e42")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The SampleFilePdfAdobeAcrobatProDCTAppFolder folder.
        /// </summary>
        [RepositoryFolder("ed020dac-9d58-49da-94ba-bf350c7176cd")]
        public partial class SampleFilePdfAdobeAcrobatProDCTAppFolder : RepoGenBaseFolder
        {
            BellWorkflowRepositoryFolders.ToolBarFolder _toolbar;
            ShareButtonInfoClass _sharebuttonInfo;
            RepoItemInfo _emailfieldInfo;
            RepoItemInfo _donebuttonInfo;
            RepoItemInfo _sharefileforviewingorcommentingandInfo;
            RepoItemInfo _toolbar1Info;

            /// <summary>
            /// Creates a new SampleFilePdfAdobeAcrobatProDCT  folder.
            /// </summary>
            public SampleFilePdfAdobeAcrobatProDCTAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SampleFilePdfAdobeAcrobatProDCT", "/form[@title>'SampleFile.pdf - Adobe Acrobat']", parentFolder, 30000, null, true, "ed020dac-9d58-49da-94ba-bf350c7176cd", "")
            {
                _toolbar = new BellWorkflowRepositoryFolders.ToolBarFolder(this);
                _sharebuttonInfo = new ShareButtonInfoClass(this);
                _emailfieldInfo = new RepoItemInfo(this, "Emailfield", "element[@instance='1']/?/?/element[@instance='4']/element[@instance='0']/element[@instance='0']/element[@instance='0']", 30000, null, "35f1303b-5bbf-4ecf-8c66-05a867fff6e2");
                _donebuttonInfo = new RepoItemInfo(this, "DoneButton", "element[@instance='1']/element[@instance='0']/element[@instance='1']", 30000, null, "68bc3b9e-422d-4e6a-a0af-007190e73e31");
                _sharefileforviewingorcommentingandInfo = new RepoItemInfo(this, "ShareFileForViewingOrCommentingAnd", "element[@instance='1']/element[@instance='0']/element[@instance='0']/toolbar[1]/container[3]/container[2]/button[@accessiblename>'Share file for viewing or']", 30000, null, "8514c70f-49f5-4079-8302-aee4d5ab96a9");
                _toolbar1Info = new RepoItemInfo(this, "ToolBar1", "container[@controlid='1000']/element[@controlid='1100']/toolbar[@accessiblerole='ToolBar']", 30000, null, "2647b994-a1c7-43ce-ba73-3c3797c94b0a");
            }

            /// <summary>
            /// The ShareButtonInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("fb0aa0aa-2063-4d6e-b0c3-5a3317a66898")]
            public class ShareButtonInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ShareButtonInfoClass class constructor.
                /// </summary>
                public ShareButtonInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ShareButton", "element[@instance='1']/element[@instance='0']/element[@instance='0']", 30000, null, "fb0aa0aa-2063-4d6e-b0c3-5a3317a66898")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("2022eca7-c472-442b-bc40-d70776a155a7")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("2022eca7-c472-442b-bc40-d70776a155a7");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("2022eca7-c472-442b-bc40-d70776a155a7")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("2022eca7-c472-442b-bc40-d70776a155a7", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ed020dac-9d58-49da-94ba-bf350c7176cd")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ed020dac-9d58-49da-94ba-bf350c7176cd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ShareButton item.
            /// </summary>
            [RepositoryItem("fb0aa0aa-2063-4d6e-b0c3-5a3317a66898")]
            public virtual Ranorex.Unknown ShareButton
            {
                get
                {
                    return _sharebuttonInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ShareButton item info.
            /// </summary>
            [RepositoryItemInfo("fb0aa0aa-2063-4d6e-b0c3-5a3317a66898")]
            public virtual ShareButtonInfoClass ShareButtonInfo
            {
                get
                {
                    return _sharebuttonInfo;
                }
            }

            /// <summary>
            /// The Emailfield item.
            /// </summary>
            [RepositoryItem("35f1303b-5bbf-4ecf-8c66-05a867fff6e2")]
            public virtual Ranorex.Unknown Emailfield
            {
                get
                {
                    return _emailfieldInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Emailfield item info.
            /// </summary>
            [RepositoryItemInfo("35f1303b-5bbf-4ecf-8c66-05a867fff6e2")]
            public virtual RepoItemInfo EmailfieldInfo
            {
                get
                {
                    return _emailfieldInfo;
                }
            }

            /// <summary>
            /// The DoneButton item.
            /// </summary>
            [RepositoryItem("68bc3b9e-422d-4e6a-a0af-007190e73e31")]
            public virtual Ranorex.Unknown DoneButton
            {
                get
                {
                    return _donebuttonInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The DoneButton item info.
            /// </summary>
            [RepositoryItemInfo("68bc3b9e-422d-4e6a-a0af-007190e73e31")]
            public virtual RepoItemInfo DoneButtonInfo
            {
                get
                {
                    return _donebuttonInfo;
                }
            }

            /// <summary>
            /// The ShareFileForViewingOrCommentingAnd item.
            /// </summary>
            [RepositoryItem("8514c70f-49f5-4079-8302-aee4d5ab96a9")]
            public virtual Ranorex.Button ShareFileForViewingOrCommentingAnd
            {
                get
                {
                    return _sharefileforviewingorcommentingandInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ShareFileForViewingOrCommentingAnd item info.
            /// </summary>
            [RepositoryItemInfo("8514c70f-49f5-4079-8302-aee4d5ab96a9")]
            public virtual RepoItemInfo ShareFileForViewingOrCommentingAndInfo
            {
                get
                {
                    return _sharefileforviewingorcommentingandInfo;
                }
            }

            /// <summary>
            /// The ToolBar1 item.
            /// </summary>
            [RepositoryItem("2647b994-a1c7-43ce-ba73-3c3797c94b0a")]
            public virtual Ranorex.ToolBar ToolBar1
            {
                get
                {
                    return _toolbar1Info.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The ToolBar1 item info.
            /// </summary>
            [RepositoryItemInfo("2647b994-a1c7-43ce-ba73-3c3797c94b0a")]
            public virtual RepoItemInfo ToolBar1Info
            {
                get
                {
                    return _toolbar1Info;
                }
            }

            /// <summary>
            /// The ToolBar folder.
            /// </summary>
            [RepositoryFolder("fecf148b-6692-4cf7-a702-21366e76c5c2")]
            public virtual BellWorkflowRepositoryFolders.ToolBarFolder ToolBar
            {
                get { return _toolbar; }
            }
        }

        /// <summary>
        /// The ToolBarFolder folder.
        /// </summary>
        [RepositoryFolder("fecf148b-6692-4cf7-a702-21366e76c5c2")]
        public partial class ToolBarFolder : RepoGenBaseFolder
        {
            RepoItemInfo _somemenuitemInfo;
            RepoItemInfo _somemenuitem1Info;
            RepoItemInfo _somemenuitem2Info;

            /// <summary>
            /// Creates a new ToolBar  folder.
            /// </summary>
            public ToolBarFolder(RepoGenBaseFolder parentFolder) :
                    base("ToolBar", ".//toolbar[@accessiblerole='ToolBar']", parentFolder, 30000, null, false, "fecf148b-6692-4cf7-a702-21366e76c5c2", "")
            {
                _somemenuitemInfo = new RepoItemInfo(this, "SomeMenuItem", "menuitem[@accessiblename='🗖']", 30000, null, "b3077bf8-47d8-4b09-a7b5-0c3c739465a8");
                _somemenuitem1Info = new RepoItemInfo(this, "SomeMenuItem1", "menuitem[@accessiblename='🗗']", 30000, null, "98b7284d-0286-4a28-a47d-b46d757c079c");
                _somemenuitem2Info = new RepoItemInfo(this, "SomeMenuItem2", "menuitem[@accessiblename='🗙']", 30000, null, "b1ee9508-f35e-4a97-bff8-d4f5a4881b66");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fecf148b-6692-4cf7-a702-21366e76c5c2")]
            public virtual Ranorex.ToolBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fecf148b-6692-4cf7-a702-21366e76c5c2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeMenuItem item.
            /// </summary>
            [RepositoryItem("b3077bf8-47d8-4b09-a7b5-0c3c739465a8")]
            public virtual Ranorex.MenuItem SomeMenuItem
            {
                get
                {
                    return _somemenuitemInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The SomeMenuItem item info.
            /// </summary>
            [RepositoryItemInfo("b3077bf8-47d8-4b09-a7b5-0c3c739465a8")]
            public virtual RepoItemInfo SomeMenuItemInfo
            {
                get
                {
                    return _somemenuitemInfo;
                }
            }

            /// <summary>
            /// The SomeMenuItem1 item.
            /// </summary>
            [RepositoryItem("98b7284d-0286-4a28-a47d-b46d757c079c")]
            public virtual Ranorex.MenuItem SomeMenuItem1
            {
                get
                {
                    return _somemenuitem1Info.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The SomeMenuItem1 item info.
            /// </summary>
            [RepositoryItemInfo("98b7284d-0286-4a28-a47d-b46d757c079c")]
            public virtual RepoItemInfo SomeMenuItem1Info
            {
                get
                {
                    return _somemenuitem1Info;
                }
            }

            /// <summary>
            /// The SomeMenuItem2 item.
            /// </summary>
            [RepositoryItem("b1ee9508-f35e-4a97-bff8-d4f5a4881b66")]
            public virtual Ranorex.MenuItem SomeMenuItem2
            {
                get
                {
                    return _somemenuitem2Info.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The SomeMenuItem2 item info.
            /// </summary>
            [RepositoryItemInfo("b1ee9508-f35e-4a97-bff8-d4f5a4881b66")]
            public virtual RepoItemInfo SomeMenuItem2Info
            {
                get
                {
                    return _somemenuitem2Info;
                }
            }
        }

        /// <summary>
        /// The SampleFilePdfOpenedFromAdobeDocumeAppFolder folder.
        /// </summary>
        [RepositoryFolder("3ce5c783-f83a-45c4-b2ef-e9984fea4ed1")]
        public partial class SampleFilePdfOpenedFromAdobeDocumeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _avlavviewInfo;
            RepoItemInfo _copysharedlinkInfo;
            RepoItemInfo _donebuttonInfo;
            RepoItemInfo _avlavview1Info;

            /// <summary>
            /// Creates a new SampleFilePdfOpenedFromAdobeDocume  folder.
            /// </summary>
            public SampleFilePdfOpenedFromAdobeDocumeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SampleFilePdfOpenedFromAdobeDocume", "/form[@title>'SampleFile.pdf (Opened from']", parentFolder, 30000, null, true, "3ce5c783-f83a-45c4-b2ef-e9984fea4ed1", "")
            {
                _avlavviewInfo = new RepoItemInfo(this, "AVLAVView", "element[@instance='0']/element[@instance='0']", 30000, null, "929c83bc-b1ea-4911-8840-e30b557c17d7");
                _copysharedlinkInfo = new RepoItemInfo(this, "CopySharedLink", "element[@instance='1']/?/?/element[@instance='4']/element[@instance='0']/element[@instance='0']/element[@instance='0']", 30000, null, "11e95966-aa97-4d4c-9d59-8e08ab122839");
                _donebuttonInfo = new RepoItemInfo(this, "DoneButton", "element[@instance='1']/element[@instance='0']/element[@instance='1']", 30000, null, "ced54d1c-a75a-4e04-9372-706cb2cf69dd");
                _avlavview1Info = new RepoItemInfo(this, "AVLAVView1", "element[@instance='0']", 30000, null, "5883ae7d-d40d-41c1-9b77-84c57c918dbb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3ce5c783-f83a-45c4-b2ef-e9984fea4ed1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3ce5c783-f83a-45c4-b2ef-e9984fea4ed1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AVLAVView item.
            /// </summary>
            [RepositoryItem("929c83bc-b1ea-4911-8840-e30b557c17d7")]
            public virtual Ranorex.Unknown AVLAVView
            {
                get
                {
                    return _avlavviewInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The AVLAVView item info.
            /// </summary>
            [RepositoryItemInfo("929c83bc-b1ea-4911-8840-e30b557c17d7")]
            public virtual RepoItemInfo AVLAVViewInfo
            {
                get
                {
                    return _avlavviewInfo;
                }
            }

            /// <summary>
            /// The CopySharedLink item.
            /// </summary>
            [RepositoryItem("11e95966-aa97-4d4c-9d59-8e08ab122839")]
            public virtual Ranorex.Unknown CopySharedLink
            {
                get
                {
                    return _copysharedlinkInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The CopySharedLink item info.
            /// </summary>
            [RepositoryItemInfo("11e95966-aa97-4d4c-9d59-8e08ab122839")]
            public virtual RepoItemInfo CopySharedLinkInfo
            {
                get
                {
                    return _copysharedlinkInfo;
                }
            }

            /// <summary>
            /// The DoneButton item.
            /// </summary>
            [RepositoryItem("ced54d1c-a75a-4e04-9372-706cb2cf69dd")]
            public virtual Ranorex.Unknown DoneButton
            {
                get
                {
                    return _donebuttonInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The DoneButton item info.
            /// </summary>
            [RepositoryItemInfo("ced54d1c-a75a-4e04-9372-706cb2cf69dd")]
            public virtual RepoItemInfo DoneButtonInfo
            {
                get
                {
                    return _donebuttonInfo;
                }
            }

            /// <summary>
            /// The AVLAVView1 item.
            /// </summary>
            [RepositoryItem("5883ae7d-d40d-41c1-9b77-84c57c918dbb")]
            public virtual Ranorex.Unknown AVLAVView1
            {
                get
                {
                    return _avlavview1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The AVLAVView1 item info.
            /// </summary>
            [RepositoryItemInfo("5883ae7d-d40d-41c1-9b77-84c57c918dbb")]
            public virtual RepoItemInfo AVLAVView1Info
            {
                get
                {
                    return _avlavview1Info;
                }
            }
        }

        /// <summary>
        /// The AdobeLicensingAppFolder folder.
        /// </summary>
        [RepositoryFolder("1775bb76-1993-43fe-b7ca-7fc02ae0d72c")]
        public partial class AdobeLicensingAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _spantagokInfo;
            RepoItemInfo _signoutInfo;

            /// <summary>
            /// Creates a new AdobeLicensing  folder.
            /// </summary>
            public AdobeLicensingAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AdobeLicensing", "/dom[@domain='workflow.licenses.adobe.com']", parentFolder, 30000, null, false, "1775bb76-1993-43fe-b7ca-7fc02ae0d72c", "")
            {
                _spantagokInfo = new RepoItemInfo(this, "SpanTagOK", ".//div[#'ngl-page-container']/div[4]//span[@innertext='OK']", 30000, null, "cf5cb781-b177-401c-8015-52054cf3ecd5");
                _signoutInfo = new RepoItemInfo(this, "SignOut", ".//div[#'ngl-page-container']/div[4]//span[@innertext='Sign out']", 30000, null, "21dc293e-ce1a-4aee-a22e-f3623397b39f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1775bb76-1993-43fe-b7ca-7fc02ae0d72c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1775bb76-1993-43fe-b7ca-7fc02ae0d72c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SpanTagOK item.
            /// </summary>
            [RepositoryItem("cf5cb781-b177-401c-8015-52054cf3ecd5")]
            public virtual Ranorex.SpanTag SpanTagOK
            {
                get
                {
                    return _spantagokInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagOK item info.
            /// </summary>
            [RepositoryItemInfo("cf5cb781-b177-401c-8015-52054cf3ecd5")]
            public virtual RepoItemInfo SpanTagOKInfo
            {
                get
                {
                    return _spantagokInfo;
                }
            }

            /// <summary>
            /// The SignOut item.
            /// </summary>
            [RepositoryItem("21dc293e-ce1a-4aee-a22e-f3623397b39f")]
            public virtual Ranorex.SpanTag SignOut
            {
                get
                {
                    return _signoutInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SignOut item info.
            /// </summary>
            [RepositoryItemInfo("21dc293e-ce1a-4aee-a22e-f3623397b39f")]
            public virtual RepoItemInfo SignOutInfo
            {
                get
                {
                    return _signoutInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
