///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BellWorkflow
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GitCheckGirija recording.
    /// </summary>
    [TestModule("6ce50ca2-1841-4319-bad3-c4e92f67d8a0", ModuleType.Recording, 1)]
    public partial class GitCheckGirija : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BellWorkflowRepository repository.
        /// </summary>
        public static BellWorkflowRepository repo = BellWorkflowRepository.Instance;

        static GitCheckGirija instance = new GitCheckGirija();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GitCheckGirija()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GitCheckGirija Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AdobeID.Continue' at 20;9.", repo.AdobeID.ContinueInfo, new RecordItemIndex(0));
            repo.AdobeID.Continue.MoveTo("20;9");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'AdobeID.Continue' at 28;1.", repo.AdobeID.ContinueInfo, new RecordItemIndex(1));
            repo.AdobeID.Continue.MoveTo("28;1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AdobeID.CanvasGrid' at 690;380.", repo.AdobeID.CanvasGridInfo, new RecordItemIndex(2));
            repo.AdobeID.CanvasGrid.MoveTo("690;380");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
