///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BellWorkflow
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OpenFile recording.
    /// </summary>
    [TestModule("84007769-f096-48be-b664-7dfb53641495", ModuleType.Recording, 1)]
    public partial class OpenFile : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BellWorkflowRepository repository.
        /// </summary>
        public static BellWorkflowRepository repo = BellWorkflowRepository.Instance;

        static OpenFile instance = new OpenFile();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OpenFile()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OpenFile Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdobeAcrobatProDCTrunk05242020.File' at 18;19.", repo.AdobeAcrobatProDCTrunk05242020.FileInfo, new RecordItemIndex(0));
            repo.AdobeAcrobatProDCTrunk05242020.File.Click("18;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Acrobat.OpenCtrlPlusO' at 58;18.", repo.Acrobat.OpenCtrlPlusOInfo, new RecordItemIndex(1));
            repo.Acrobat.OpenCtrlPlusO.Click("58;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Open.SystemItemNameDisplay' at 58;8.", repo.Open.SystemItemNameDisplayInfo, new RecordItemIndex(2));
            repo.Open.SystemItemNameDisplay.MoveTo("58;8");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Open.SystemItemNameDisplay' at 58;8.", repo.Open.SystemItemNameDisplayInfo, new RecordItemIndex(3));
            repo.Open.SystemItemNameDisplay.MoveTo("58;8");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Open.SystemItemNameDisplay' at 58;8.", repo.Open.SystemItemNameDisplayInfo, new RecordItemIndex(4));
            repo.Open.SystemItemNameDisplay.DoubleClick("58;8");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
