///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BellWorkflow
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ShareFile recording.
    /// </summary>
    [TestModule("2d63b32d-f38f-42f9-ae0d-85134f97dc1a", ModuleType.Recording, 1)]
    public partial class ShareFile : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BellWorkflowRepository repository.
        /// </summary>
        public static BellWorkflowRepository repo = BellWorkflowRepository.Instance;

        static ShareFile instance = new ShareFile();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ShareFile()
        {
            NewVariable = "Copy Shared Link";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ShareFile Instance
        {
            get { return instance; }
        }

#region Variables

        string _NewVariable;

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("36bba2b8-d410-4724-89b9-c098ddbc71f0")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "Going to Click Shared Button", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleFilePdfAdobeAcrobatProDCT.ShareButton' at 1888;24.", repo.SampleFilePdfAdobeAcrobatProDCT.ShareButtonInfo, new RecordItemIndex(1));
            repo.SampleFilePdfAdobeAcrobatProDCT.ShareButton.Click("1888;24");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleFilePdfAdobeAcrobatProDCT.ShareFileForViewingOrCommentingAnd' at 10;15.", repo.SampleFilePdfAdobeAcrobatProDCT.ShareFileForViewingOrCommentingAndInfo, new RecordItemIndex(2));
            //repo.SampleFilePdfAdobeAcrobatProDCT.ShareFileForViewingOrCommentingAnd.Click("10;15");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShareButtonClick' at 963;25.", repo.ShareButtonClickInfo, new RecordItemIndex(3));
            //repo.ShareButtonClick.Click("963;25");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(4));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShareLinkWithOthers.EmailIdField' at 164;71.", repo.ShareLinkWithOthers.EmailIdFieldInfo, new RecordItemIndex(5));
            repo.ShareLinkWithOthers.EmailIdField.Click("164;71");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(6));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'esigntestuserprod{RShiftKey down}+{RShiftKey up}proteam{LShiftKey down}@{LShiftKey up}gmail.com' with focus on 'ShareLinkWithOthers.EmailIdField'.", repo.ShareLinkWithOthers.EmailIdFieldInfo, new RecordItemIndex(7));
            repo.ShareLinkWithOthers.EmailIdField.PressKeys("esigntestuserprod{RShiftKey down}+{RShiftKey up}proteam{LShiftKey down}@{LShiftKey up}gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(8));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ShareLinkWithOthers.EmailIdField'.", repo.ShareLinkWithOthers.EmailIdFieldInfo, new RecordItemIndex(9));
            repo.ShareLinkWithOthers.EmailIdField.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(10));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShareLinkWithOthers.EmailIdField' at 343;352.", repo.ShareLinkWithOthers.EmailIdFieldInfo, new RecordItemIndex(11));
            repo.ShareLinkWithOthers.EmailIdField.Click("343;352");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(12));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab up}{LShiftKey up}{RShiftKey up}{LControlKey up}{RControlKey up}{Tab up}{LMenu up}{Tab up}{RMenu up}{Tab up}{Tab up}{LShiftKey up}{RShiftKey up}{LControlKey up}{RControlKey up}{Tab up}{LMenu up}{Tab up}{RMenu up}{Tab up}' with focus on 'SampleFilePdfOpenedFromAdobeDocume'.", repo.SampleFilePdfOpenedFromAdobeDocume.SelfInfo, new RecordItemIndex(13));
            repo.SampleFilePdfOpenedFromAdobeDocume.Self.EnsureVisible();
            Keyboard.Press("{Tab up}{LShiftKey up}{RShiftKey up}{LControlKey up}{RControlKey up}{Tab up}{LMenu up}{Tab up}{RMenu up}{Tab up}{Tab up}{LShiftKey up}{RShiftKey up}{LControlKey up}{RControlKey up}{Tab up}{LMenu up}{Tab up}{RMenu up}{Tab up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 30s.", new RecordItemIndex(14));
            Delay.Duration(30000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SampleFilePdfOpenedFromAdobeDocume.CopySharedLink'.", repo.SampleFilePdfOpenedFromAdobeDocume.CopySharedLinkInfo, new RecordItemIndex(15));
            Validate.Exists(repo.SampleFilePdfOpenedFromAdobeDocume.CopySharedLinkInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(16));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleFilePdfOpenedFromAdobeDocume.DoneButton' at 1869;21.", repo.SampleFilePdfOpenedFromAdobeDocume.DoneButtonInfo, new RecordItemIndex(17));
            repo.SampleFilePdfOpenedFromAdobeDocume.DoneButton.Click("1869;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(18));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CloseSharedFile.ButtonOK' at 49;7.", repo.CloseSharedFile.ButtonOKInfo, new RecordItemIndex(19));
            repo.CloseSharedFile.ButtonOK.Click("49;7");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleFilePdfOpenedFromAdobeDocume.DoneButton' at 933;20.", repo.SampleFilePdfOpenedFromAdobeDocume.DoneButtonInfo, new RecordItemIndex(20));
            //repo.SampleFilePdfOpenedFromAdobeDocume.DoneButton.Click("933;20");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CloseSharedFile.ButtonOK' at 19;10.", repo.CloseSharedFile.ButtonOKInfo, new RecordItemIndex(21));
            //repo.CloseSharedFile.ButtonOK.Click("19;10");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(22));
            Delay.Duration(1000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
