///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BellWorkflow
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SignOut recording.
    /// </summary>
    [TestModule("cec83af1-ed4c-4882-b6e8-4bfddec2a4dd", ModuleType.Recording, 1)]
    public partial class SignOut : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BellWorkflowRepository repository.
        /// </summary>
        public static BellWorkflowRepository repo = BellWorkflowRepository.Instance;

        static SignOut instance = new SignOut();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SignOut()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SignOut Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdobeAcrobatProDCTrunk05242020.ClickProfile' at 964;14.", repo.AdobeAcrobatProDCTrunk05242020.ClickProfileInfo, new RecordItemIndex(0));
            //repo.AdobeAcrobatProDCTrunk05242020.ClickProfile.Click("964;14");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(1));
            //Delay.Duration(5000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PressSignOutFromProfile' at 63;158.", repo.PressSignOutFromProfile.SelfInfo, new RecordItemIndex(2));
            //repo.PressSignOutFromProfile.Self.Click("63;158");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(3));
            //Delay.Duration(10000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdobeLicensing' at 711;309.", repo.AdobeLicensing.SelfInfo, new RecordItemIndex(4));
            //repo.AdobeLicensing.Self.Click("711;309");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 30s.", new RecordItemIndex(5));
            //Delay.Duration(30000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdobeAcrobatProDCTrunk05242020.ClickProfile' at 1892;21.", repo.AdobeAcrobatProDCTrunk05242020.ClickProfileInfo, new RecordItemIndex(6));
            //repo.AdobeAcrobatProDCTrunk05242020.ClickProfile.Click("1892;21");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(7));
            //Delay.Duration(5000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PressSignOutFromProfile' at 75;165.", repo.PressSignOutFromProfile.SelfInfo, new RecordItemIndex(8));
            //repo.PressSignOutFromProfile.Self.Click("75;165");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(9));
            //Delay.Duration(10000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdobeLicensing' at 711;309.", repo.AdobeLicensing.SelfInfo, new RecordItemIndex(10));
            //repo.AdobeLicensing.Self.Click("711;309");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleFilePdfOpenedFromAdobeDocume.AVLAVView1' at 1892;18.", repo.SampleFilePdfOpenedFromAdobeDocume.AVLAVView1Info, new RecordItemIndex(11));
            repo.SampleFilePdfOpenedFromAdobeDocume.AVLAVView1.Click("1892;18");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(12));
            //Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PressSignOutFromProfile' at 45;161.", repo.PressSignOutFromProfile.SelfInfo, new RecordItemIndex(13));
            repo.PressSignOutFromProfile.Self.Click("45;161");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(14));
            //Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdobeLicensing.SignOut' at 18;2.", repo.AdobeLicensing.SignOutInfo, new RecordItemIndex(15));
            repo.AdobeLicensing.SignOut.Click("18;2");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(16));
            //Delay.Duration(10000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
