///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SecondMyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SecondMyTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c57fb4a0-9c91-4139-8800-71df14bb6451")]
    public partial class SecondMyTestRepository : RepoGenBaseFolder
    {
        static SecondMyTestRepository instance = new SecondMyTestRepository();

        /// <summary>
        /// Gets the singleton class instance representing the SecondMyTestRepository element repository.
        /// </summary>
        [RepositoryFolder("c57fb4a0-9c91-4139-8800-71df14bb6451")]
        public static SecondMyTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SecondMyTestRepository() 
            : base("SecondMyTestRepository", "/", null, 0, false, "c57fb4a0-9c91-4139-8800-71df14bb6451", ".\\RepositoryImages\\SecondMyTestRepositoryc57fb4a0.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c57fb4a0-9c91-4139-8800-71df14bb6451")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class SecondMyTestRepositoryFolders
    {
    }
#pragma warning restore 0436
}
